---
mealie_oidc_auth_enabled: true
mealie_oidc_provider_name: authentik
mealie_oidc_configuration_url: "https://authentik.{{ domain_name }}/application/o/mealie/.well-known/openid-configuration"
mealie_oidc_client_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30633938623062666637636439326631353164306237303531633863616636363539313964303563
          6132396462326463396632323831316231353562356431320a366133623538393663343533316235
          37663165323039363531626532343935663666333365613162623836383130393735363761666432
          6461373165343236390a323236313739333836616438353264643739646665633863373433623130
          38323732656365616138376430303033336364303732383963653239616232666437343530626134
          6539646266383435373065336462393833366331336136346631
mealie_oidc_client_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61363930343565306361643766326339383336613637663033313736383566666637336466656231
          3039643237633362303865386130633135336632663835340a376136663632336338333632326539
          30633235373066663832626533303930613230656463343965346565306566373833373533336130
          3632653434353639380a643863616530653038613238376233393665323463663739366536626132
          35386530396439666532386631626330343034363733363336383865366262346632383134356530
          64303666666366306665343763356462633233366564346665666138306434386365373962336364
          64386333663838646466343936616131353137323633353530393939623430623261303563386433
          36363237353437343830376437383633386363303033323063626463653862333662313939643963
          65656131653630336632656633633866356662613736323439366431646339336537383162646361
          30363264613730323233333266363061353232373766376365376138373166313133396435623933
          633930336430343637656666366264323534
mealie_oidc_signup_enabled: true
mealie_oidc_user_group: mealie-users
mealie_oidc_admin_group: mealie-admins
mealie_oidc_auto_redirect: true
mealie_oidc_remember_me: false
mealie_allow_signup: false
mealie_puid: 1000
mealie_pgid: 1000
mealie_tz: America/Chicago
mealie_base_url: "https://mealie.{{ domain_name }}"
mealie_db_engine: postgres
mealie_postgres_user: mealie
mealie_postgres_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63393937633863316332353661333239356337643533316439336234366165373037653065353066
          3439633935316338303834343465633861633833323232330a663436323937303861336361303931
          36353961636466393461383638646530323636386134363937366338303462626365393764343463
          6262316339316532360a333263366636613232643564313435633730383264326232376630643262
          3432
mealie_postgres_server: postgres
mealie_postgres_port: 5432
mealie_postgres_db: mealie
