---
ansible_ssh_common_args: '-o "SetEnv TERM=dumb" -o "StrictHostKeyChecking=no"'
ansible_user: admin
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
k3s_version: v1.34.2+k3s1
token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38353039356165613332363864646366383065656263613737323932326662333866326466346638
          6331323162343433383461313533366364313131653464320a343332306632356165623762633834
          38376466313339396161313339393939376138653038383937343963393966653033323561396164
          3262386462616664630a323439366461666266376166643835343964333162643832613637373034
          63306461636661316465313239343136623538366238366635616531353134313032636461373037
          63663961666134613639333339623063613437353937346161383838656366363737623636653035
          30666635356464366433396565326363373766396235663533313566626637646134376132643833
          31373362393532306162373263353333663134376465376635396138656237326363653536383838
          3034
extra_server_args: "--cluster-cidr=10.50.0.0/16 --service-cidr=10.51.0.0/16 --cluster-dns=10.51.0.10"
# extra_agent_args: ""
