---
authentik_image_tag: 2025.10.2
authentik_error_reporting: true
authentik_pg_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62346638336537616439306635333466366462663133353964663239373035313635363065373166
          3263333638653432303332613362386232333832366530330a656437363762313964383833643332
          62643965303265383830323038616663383165353437373833306530323530626535636262643161
          3461626132323239640a383465316238666466313365666535666433366536633339626230373636
          61333934393731343639373432633564633234346338313838336636636433306464303865646434
          33623038613362643762383230383338613162373964613435323335636538663965353636363237
          386232653963363764646361373066393133
authentik_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33366464376266386263623063626166353037666535346236306232383661376564336662303566
          6265653264396163663137313363363963376234333165370a346563666365656561303737393435
          64336431613036373131373765366335636137323334373438393836333836363034343565303738
          3935653963643438390a333364633330376365656164666363653934613536653330346330633937
          65346461323637663765646534656165646632306339623132396464623862303131346238393161
          30643432326531353466363836306535303338386463306333313037393430323639303132613061
          35346361383266353235386162646131373239313165383433653434326332666233383262383533
          34306264303364663333376433643662383437653863623963613730663230656661646239353435
          3266
authentik_smtp_host: localhost
authentik_smtp_port: 25
authentik_smtp_username: akadmin
authentik_smtp_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316333323739333933356433633339343738393466316537383037376361316661313030396362
          3761366330633531333036323539646436386366313562390a363633323261666664366461623462
          30396533316461323634653537346439353331363531616530323933623966636434346233343361
          3739393333333537640a316361346634633762343438333266373338353439363038316661633633
          3137
authentik_smtp_tls: false
authentik_smtp_ssl: false
authentik_smtp_from: authentik@localhost
authentik_bootstrap_password:
authentik_bootstrap_token:
