---
caddy_cloudflare_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32373030663830636265303365383833643563316433366434636665336130373165363439633437
          6535623738656465386435306231303530363932396436370a336563303030616635613665633831
          39333634626335346430323731323431616462323133323238313133333232643863663665376239
          3137633666346666380a363264633966666466346535653232653131393239656139353036386631
          38343737653532396261386565366563346537343736636364333264346134373239383939303832
          3333363131626133363739393266356465313261393630646130
caddy_dir: /opt/caddy
caddy_ts_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33323730326333643939363265643737623633326430363335633338343761623530656666653861
          3263376239306435633335663838633937373332646362610a306431303761636364653362646161
          36363561633864613166326632646361663934353639666133613964643639633037303439306632
          3638303432613665370a626331333639343235623132663639633539643833386431653437313231
          37373733646563636634376233626136356434316264353732663736653538393439323830636663
          61393635633566653966326636363963643563323639306237626266643264383634616235643131
          613334333739373565333935303339393134
