---
caddy_cloudflare_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32373030663830636265303365383833643563316433366434636665336130373165363439633437
          6535623738656465386435306231303530363932396436370a336563303030616635613665633831
          39333634626335346430323731323431616462323133323238313133333232643863663665376239
          3137633666346666380a363264633966666466346535653232653131393239656139353036386631
          38343737653532396261386565366563346537343736636364333264346134373239383939303832
          3333363131626133363739393266356465313261393630646130
