---
paperless_ngx_db_type: sqlite
paperless_ngx_conf_apps: allauth.socialaccount.providers.openid_connect
paperless_ngx_conf_dbpass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316333323739333933356433633339343738393466316537383037376361316661313030396362
          3761366330633531333036323539646436386366313562390a363633323261666664366461623462
          30396533316461323634653537346439353331363531616530323933623966636434346233343361
          3739393333333537640a316361346634633762343438333266373338353439363038316661633633
          3137
paperless_ngx_conf_socialaccount_providers: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31343666336365363232656231626465666437333261633138333864633363366134633063313736
          3630343434616338333463656131396134376331636334390a393964636638336564333938323032
          32353434646235663464373362316135376234653632373061633130316262306330633631386337
          3435323436323962390a326464636165663637333531643430666138643530653066353134623463
          65333639383263663235326361656530376239323562313836613737383835636366613766396465
          63353564313838323263396565303066353137356265663734366166333030393563656132643530
          39613535306366303837303366383234646631343933303765636239366263383336383462656337
          62626136653830666434626566343738633763363334373264383437353162383837633564623864
          30373435383035653561336264326361636430643963643630353934613635303739623330366632
          63323435303739346461373965316331636362636435613466373835323932623738333264646661
          63626332373534343239333134636638343238393134623535393064646634643838346232383532
          35356334393432383561616230303538353465316462616538616331666232653962353431646432
          34626236383339663838346335393835643032616432396265343030613962353234663736626635
          63613661353234393635343030343836306434653730623536303264386562656434323234636330
          63663033373663353232373164393830306538633562356534316665373835613936643330666231
          37623265623666313064616631623862663532313034623965666237626335383431313461656639
          63353030646539316430353738303561653732393265643263633930373133373330353232666434
          36343931386163643566333036326637643432626330303061303631653636363431303165306334
          62363065663564356162643136383437396234383937303437363637346434363630383530353739
          65646233316265626438373038383639333132616464626238323161383739313731373831663134
          63363166616164393863303365623062386633616164363563383931643137393966303736633363
          35643032323331623364303534613033343734303837373764613465393737643732323038633438
          39313162313937396464623564353163643066303637663338373464613238336262333434333534
          65376161646662376238346130376530613763613238363763303530393038666130656362633034
          65353538643463653130306334306132643663333934333733303761306630636665
paperless_ngx_conf_tika_enabled: true
paperless_ngx_conf_time_zone: America/Chicago
paperless_ngx_conf_url: "https://paperless.{{ domain_name }}"
paperless_ngx_dir_python: /usr
paperless_ngx_dir_runtime_data: /mnt/paperless
paperless_ngx_system_group: root
paperless_ngx_system_user: root
